"""Generate evals/cases/*.yaml (developer tool; the YAML files are committed and are the source of truth for tests).

    uv run python scripts/make_fixtures.py

Every applicant is synthetic and every document is plain text marked SPECIMEN. Sanctions-hit cases
use deliberate fuzzy variants of public UN list names (see docs/DECISIONS.md D-18). The expected
values for hits come from the vendored snapshot and are checked by tests/test_fixtures.py.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

OUT = Path(__file__).resolve().parent.parent / "evals" / "cases"
HEADER = (
    "# SPECIMEN: synthetic test case. Fictional applicant, no real documents or ID numbers.\n"
    "# Generated by scripts/make_fixtures.py; see docs/EVALS.md for the format.\n"
)
STD = ["intake", "extract", "screen", "assess", "approve"]
REQ = ["screen", "assess", "approve"]


def doc(case_id: str, doc_type: str) -> dict[str, str]:
    return {
        "doc_type": doc_type,
        "content": f"SPECIMEN - SYNTHETIC TEST DOCUMENT, NOT A REAL DOCUMENT\ncase={case_id}\ndoc_type={doc_type}\n",
    }


def field(
    name: str, value: str | None, conf: float, review: bool = False, reason: str | None = None
) -> dict[str, Any]:
    return {
        "name": name,
        "value": value,
        "confidence": conf,
        "needs_review": review,
        "reason": reason,
        "reviewed": False,
    }


def id_response(a: dict[str, Any], n: int, low: dict[str, float] | None = None) -> dict[str, Any]:
    low = low or {}
    vals = {
        "full_name": a["name"],
        "date_of_birth": a["dob"],
        "id_number": f"SPEC-ID-{n:04d}",
        "nationality": a["nationality"],
        "expiry_date": "2031-05-14",
        "issuing_country": a["nationality"],
    }
    fields = []
    for k, v in vals.items():
        if k in low:
            fields.append(field(k, v, low[k], True, "low_confidence"))
        else:
            fields.append(field(k, v, 0.97))
    flagged = any(f["needs_review"] for f in fields)
    return {
        "document_type": "id_document",
        "status": "needs_review" if flagged else "extracted",
        "needs_review": flagged,
        "fields": fields,
    }


def poa_response(a: dict[str, Any], city: str) -> dict[str, Any]:
    fields = [
        field("full_name", a["name"], 0.96),
        field("address_line", "SPECIMEN Street 1", 0.93),
        field("city", city, 0.95),
        field("issue_date", "2026-08-31", 0.97),
        field("issuer", "SPECIMEN Utility Co", 0.94),
    ]
    return {
        "document_type": "proof_of_address",
        "status": "extracted",
        "needs_review": False,
        "fields": fields,
    }


def case(
    cid: str,
    desc: str,
    a: dict[str, Any],
    n: int,
    city: str,
    expected: dict[str, Any],
    script: list[dict[str, Any]],
    *,
    docs: tuple[str, ...] = ("id_document", "proof_of_address"),
    followup: tuple[str, ...] = (),
    low: dict[str, float] | None = None,
    kyc: str = "ok",
    llm: str = "ok",
) -> dict[str, Any]:
    responses: dict[str, Any] = {}
    if kyc == "ok":
        responses = {"id_document": id_response(a, n, low), "proof_of_address": poa_response(a, city)}
    return {
        "id": cid,
        "specimen": True,
        "description": desc,
        "applicant": a,
        "documents": [doc(cid, t) for t in docs],
        "followup_documents": [doc(cid, t) for t in followup],
        "kyc_mode": kyc,
        "llm_mode": llm,
        "kyc_response": responses,
        "human_script": script,
        "expected": expected,
    }


def app(
    name: str, dob: str, nat: str, res: str, occ: str, aliases: list[str] | None = None
) -> dict[str, Any]:
    return {
        "name": name,
        "aliases": aliases or [],
        "dob": dob,
        "nationality": nat,
        "residence_country": res,
        "occupation": occ,
    }


def exp(
    rec: str,
    rating: str,
    final: str,
    traj: list[str],
    *,
    hits: list[dict[str, str]] | None = None,
    rules: list[str] | None = None,
    degraded: list[str] | None = None,
) -> dict[str, Any]:
    return {
        "recommendation": rec,
        "risk_rating": rating,
        "hits": hits or [],
        "fired_rules": rules or [],
        "final_status": final,
        "degraded": degraded or [],
        "trajectory": traj,
        "required_steps": REQ,
    }


UAE = "United Arab Emirates"
DRC = "Democratic Republic of the Congo"
APPROVE = [{"action": "approve"}]

CASES = [
    case(
        "clean_approve",
        "Clean applicant: no hits, no rules fire. A human still has to approve.",
        app("Layla Nasser Almazrouei", "1990-06-12", UAE, UAE, "Software engineer"),
        1,
        "Dubai",
        exp("approve", "low", "approved", [*STD, "execute"]),
        APPROVE,
    ),
    case(
        "true_sanctions_hit",
        "Fuzzy variant of a UN-listed name; DOB and nationality agree with the list entry.",
        app("Khawa Pangaa Mandro", "1973-08-20", DRC, "Uganda", "Import trader"),
        2,
        "Kampala",
        exp(
            "reject",
            "high",
            "rejected",
            STD,
            hits=[{"entry_id": "CDi.009", "class": "strong"}],
            rules=["R-SAN-01"],
        ),
        [{"action": "reject", "dispositions": {"CDi.009": "confirmed"}, "note": "Confirmed match"}],
    ),
    case(
        "near_miss_dob_mismatch",
        "Near-identical name to a listed person but a different DOB and nationality: false positive an officer must clear.",
        app("Douglas Iruta Mpamoh", "1991-02-14", "Uganda", UAE, "Marketing consultant"),
        3,
        "Dubai",
        exp(
            "manual_review",
            "medium",
            "approved",
            [*STD, "execute"],
            hits=[{"entry_id": "CDi.011", "class": "possible"}],
            rules=["R-SAN-02"],
        ),
        [{"action": "approve", "dispositions": {"CDi.011": "cleared"}, "note": "DOB and nationality differ"}],
    ),
    case(
        "missing_poa",
        "Proof of address missing on the first pass; provided after the officer requests more information. Expected values describe the FIRST approval pass.",
        app("Priya Menon Varghese", "1988-03-21", "India", UAE, "Accountant"),
        4,
        "Dubai",
        exp(
            "request_info",
            "medium",
            "approved",
            [*STD, "await_docs", "intake", "extract", "screen", "assess", "approve", "execute"],
            rules=["R-DOC-01"],
        ),
        [{"action": "request_more_info", "note": "Proof of address needed"}, {"action": "approve"}],
        docs=("id_document",),
        followup=("proof_of_address",),
    ),
    case(
        "low_confidence_extraction",
        "ID extraction returns low-confidence DOB and ID number; the officer verifies.",
        app("Omar Khalid Haddad", "1985-11-03", "Jordan", UAE, "Sales manager"),
        5,
        "Abu Dhabi",
        exp("manual_review", "medium", "approved", [*STD, "execute"], rules=["R-DOC-02"]),
        [{"action": "approve", "note": "Verified against the original by the officer"}],
        low={"date_of_birth": 0.62, "id_number": 0.55},
    ),
    case(
        "high_risk_jurisdiction",
        "Residence in an FATF call-for-action jurisdiction: high rating, human decides (enhanced due diligence noted).",
        app("Sofia Alvarez Romero", "1982-09-30", "Spain", "Myanmar", "Translator"),
        6,
        "Yangon",
        exp("manual_review", "high", "approved", [*STD, "execute"], rules=["R-JUR-01"]),
        [{"action": "approve", "note": "Enhanced due diligence completed"}],
    ),
    case(
        "high_risk_occupation",
        "Occupation in a higher-risk category (gold dealer).",
        app("Rashid Karim Obeng", "1979-01-17", "Ghana", UAE, "Gold dealer"),
        7,
        "Dubai",
        exp("manual_review", "medium", "approved", [*STD, "execute"], rules=["R-OCC-01"]),
        APPROVE,
    ),
    case(
        "multiple_issues",
        "Missing proof of address, low-confidence expiry date and residence in an increased-monitoring jurisdiction; three medium rules escalate the rating to high.",
        app("Anita Joseph D'Souza", "1976-07-08", "India", "Lebanon", "Consultant"),
        8,
        "Beirut",
        exp("request_info", "high", "rejected", STD, rules=["R-DOC-01", "R-DOC-02", "R-JUR-02"]),
        [{"action": "reject", "note": "Unable to complete due diligence"}],
        docs=("id_document",),
        low={"expiry_date": 0.7},
    ),
    case(
        "kyc_unavailable",
        "KYC service down: the case reaches the officer flagged extraction unavailable; approval is blocked, so the officer requests more information.",
        app("Hamza Qureshi", "1992-04-09", "Pakistan", UAE, "Civil engineer"),
        9,
        "Sharjah",
        exp(
            "manual_review",
            "high",
            "awaiting_documents",
            [*STD, "await_docs"],
            rules=["R-DOC-03"],
            degraded=["extraction_unavailable"],
        ),
        [{"action": "request_more_info", "note": "Extraction unavailable; please resubmit"}],
        kyc="unavailable",
    ),
    case(
        "llm_unavailable",
        "LLM down: summary and explanation fall back to templates; rules and screening are unaffected.",
        app("Mateo Ruiz", "1994-12-01", "Argentina", UAE, "Graphic designer"),
        10,
        "Dubai",
        exp("approve", "low", "approved", [*STD, "execute"], degraded=["llm_unavailable"]),
        APPROVE,
        llm="unavailable",
    ),
    case(
        "alias_hit",
        "Applicant's declared alias is a fuzzy variant of a listed alias; DOB and nationality agree.",
        app("Etienne Kabasele Mbuyi", "1971-05-23", DRC, UAE, "Importer", aliases=["Floribert Njabou"]),
        11,
        "Dubai",
        exp(
            "reject",
            "high",
            "rejected",
            STD,
            hits=[{"entry_id": "CDi.021", "class": "strong"}],
            rules=["R-SAN-01"],
        ),
        [
            {
                "action": "reject",
                "dispositions": {"CDi.021": "confirmed"},
                "note": "Alias matches listed alias",
            }
        ],
    ),
    case(
        "shared_given_name_no_hit",
        "Shares a given name with a listed person but is not similar enough to raise a hit.",
        app("Douglas Peterson", "1983-02-25", "Canada", UAE, "Airline pilot"),
        12,
        "Dubai",
        exp("approve", "low", "approved", [*STD, "execute"]),
        APPROVE,
    ),
]


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for c in CASES:
        text = HEADER + yaml.safe_dump(c, sort_keys=False, allow_unicode=True, width=100)
        (OUT / f"{c['id']}.yaml").write_text(text, encoding="utf-8")
    print(f"wrote {len(CASES)} cases to {OUT}")


if __name__ == "__main__":
    main()
