apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secretstore.yaml
  - postgres.yaml
  - mock-bank.yaml
  - api.yaml
  - networkpolicy.yaml
configMapGenerator:
  - name: postgres-init
    files:
      - init.sh=postgres-init.sh
generatorOptions:
  disableNameSuffixHash: true
